export const bannerCategoryData = [
  {
    id: 1,
    imagePath: "/images/Category-img1.png",
    title: "پروتِین",
    routesName: "resturant",
  },
  {
    id: 2,
    imagePath: "/images/Category-img2.png",
    title: "آبمیوه بستنی",
    routesName: "resturant",
  },
  {
    id: 3,
    imagePath: "/images/Category-img3.png",
    title: "آجیل",
    routesName: "resturant",
  },
  {
    id: 4,
    imagePath: "/images/Category-img4.png",
    title: "سایر",
    routesName: "resturant",
  },
  {
    id: 5,
    imagePath: "/images/Category-img5.png",
    title: "میوه",
    routesName: "resturant",
  },
  {
    id: 6,
    imagePath: "/images/Category-img6.png",
    title: "نانوایی",
    routesName: "resturant",
  },
  {
    id: 7,
    imagePath: "/images/Category-img7.png",
    title: "شیرینی",
    routesName: "cookies",
  },
  {
    id: 8,
    imagePath: "/images/Category-img8.png",
    title: "کافه",
    routesName: "cafe",
  },
  {
    id: 9,
    imagePath: "/images/Category-img9.png",
    title: "سوپرمارکت",
    routesName: "supermarket",
  },
  {
    id: 10,
    imagePath: "/images/Category-img10.png",
    title: "رستوران",
    routesName: "resturant",
  },
];

export const foodCategoryData = [
  {
    categoryId: 1,
    name: "ایرانی",
    routName: "irani",
    categoryImage: "/images/Cimage/R1.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی"],
      },
      {
        Id: 2,
        title: "چلوپز سهروردی",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 2,
    name: "فست فود",
    routName: "fast-food",
    categoryImage: "/images/Cimage/R2.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 3,
    name: "کباب",
    routName: "kabab",
    categoryImage: "/images/Cimage/R3.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 4,
    name: "پیتزا",
    routName: "pitza",
    categoryImage: "/images/Cimage/R4.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 5,
    name: "برگر",
    routName: "berger",
    categoryImage: "/images/Cimage/R5.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 6,
    name: "ساندویچ",
    routName: "sandwich",
    categoryImage: "/images/Cimage/R6.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 7,
    name: "سوخاری",
    routName: "sokhari",
    categoryImage: "/images/Cimage/R7.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 8,
    name: "پاستا",
    routName: "pasta",
    categoryImage: "/images/Cimage/R8.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 9,
    name: "سالاد",
    routName: "salad",
    categoryImage: "/images/Cimage/R9.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 10,
    name: "دریایی",
    routName: "sea",
    categoryImage: "/images/Cimage/R10.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 11,
    name: "بین الملل",
    routName: "international",
    categoryImage: "/images/Cimage/R11.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 12,
    name: "گیلانی",
    routName: "gilani",
    categoryImage: "/images/Cimage/R12.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
];
export const DiscountData = [
  {
    id: 1,
    resturantName: "پیتزا هات سهروردی",
    image: "/images/DiscountImage/DiscountFood1.jpeg",
    foodName: "پیتزا سالامی آمریکایی دو نفره (۳۰ سانتی متری)",
    deliveryPrice: 15000,
    price: 100000,
    discountRange: 30,
    countInStock: 82,
    rate: 3.5,
    foodIngredients: "خمیر پیتزا آمریکایی، سالامی، قارچ، پنیر پارمسان",
    comments: [
      {
        name: "سجاد",
        message: "کباب خیلی کوچیک و کم حجم بود برنج عالی طعم کباب متوسط",
        creationDate: new Date().toLocaleDateString(),
        rate: 4,
        buyProducts: ["جوجه کباب"],
      },
    ],
  },
  {
    id: 2,
    resturantName: "پیزاریوم",
    image: "/images/DiscountImage/DiscountFood2.jpeg",
    foodName: "پیتزا سوپریم (ایتالیایی) دو نفره (۳۰ سانتی متری)",
    deliveryPrice: 15000,
    price: 120000,
    discountRange: 40,
    countInStock: 62,
    rate: 3.9,
    foodIngredients:
      "خمیر پیتزا ایتالیایی، ژامبون گوشت و مرغ، سس مخصوص، زیتون اسلایسی، فلفل دلمه ای، ذرت، پنیر مخصوص، سس تک نفره",
    comments: [
      {
        name: "سجاد",
        message: "کباب خیلی کوچیک و کم حجم بود برنج عالی طعم کباب متوسط",
        creationDate: new Date().toLocaleDateString(),
        rate: 4,
        buyProducts: ["جوجه کباب"],
      },
    ],
  },
  {
    id: 3,
    resturantName: "رستوران مانی",
    image: "/images/DiscountImage/DiscountFood3.jpeg",
    foodName: "چلو کباب لقمه مخصوص",
    deliveryPrice: 15000,
    price: 220000,
    discountRange: 20,
    countInStock: 32,
    rate: 4.5,
    foodIngredients: "۲۰۰ گرم گوشت گوسفندی، برنج ایرانی، مخلفات",
    comments: [
      {
        name: "سجاد",
        message: "کباب خیلی کوچیک و کم حجم بود برنج عالی طعم کباب متوسط",
        creationDate: new Date().toLocaleDateString(),
        rate: 4,
        buyProducts: ["جوجه کباب"],
      },
    ],
  },
  {
    id: 4,
    resturantName: "ته چین بار (مطهری)",
    image: "/images/DiscountImage/DiscountFood4.jpeg",
    foodName: "ته چین باقالی پلو با ماهیچه",
    deliveryPrice: 17000,
    price: 220000,
    discountRange: 20,
    countInStock: 62,
    rate: 3.5,
    foodIngredients:
      "۱۱۰ گرم ماهیچه گوساله، ۳۵۰ گرم ته چین باقالی پلو قالبی با برنج ایرانی",
    comments: [
      {
        name: "سجاد",
        message: "کباب خیلی کوچیک و کم حجم بود برنج عالی طعم کباب متوسط",
        creationDate: new Date().toLocaleDateString(),
        rate: 4,
        buyProducts: ["جوجه کباب"],
      },
    ],
  },
  {
    id: 5,
    resturantName: "پیتزا شیلا (هفت تیر)",
    image: "/images/DiscountImage/DiscountFood6.jpeg",
    foodName: "پیتزا مخلوط (۲۳ سانتی‌ متری)",
    deliveryPrice: 12000,
    price: 170000,
    discountRange: 40,
    countInStock: 42,
    rate: 4.5,
    foodIngredients:
      "خمیر پیتزا کلاسیک ۲۳ سانتی‌ متری، ژامبون گوشت و مرغ، هات داگ فرانکفورتر، قارچ، زیتون، گوجه فرنگی، فلفل دلمه‌ ای",
    comments: [
      {
        name: "سجاد",
        message: "کباب خیلی کوچیک و کم حجم بود برنج عالی طعم کباب متوسط",
        creationDate: new Date().toLocaleDateString(),
        rate: 4,
        buyProducts: ["جوجه کباب"],
      },
    ],
  },
  {
    id: 6,
    resturantName: "ژیرا",
    image: "/images/DiscountImage/DiscountFood7.jpeg",
    foodName: "برگر ویژه ژیرا",
    deliveryPrice: 15000,
    price: 90000,
    discountRange: 30,
    countInStock: 112,
    rate: 4.5,
    foodIngredients:
      "یک عدد برگر دست ساز گوشت گوساله ۲۲۰ گرمی، فیله مرغ، بیکن ۸۰%، پنیر گودا و قارچ، نان گرد",
    comments: [
      {
        name: "سجاد",
        message: "کباب خیلی کوچیک و کم حجم بود برنج عالی طعم کباب متوسط",
        creationDate: new Date().toLocaleDateString(),
        rate: 4,
        buyProducts: ["جوجه کباب"],
      },
    ],
  },
  {
    id: 7,
    resturantName: "رستوران جوج بار",
    image: "/images/DiscountImage/DiscountFood5.jpeg",
    foodName: "چلو جوجه کباب استخوانی زعفرانی",
    deliveryPrice: 15000,
    price: 121000,
    discountRange: 40,
    countInStock: 72,
    rate: 4.5,
    foodIngredients:
      "یک سیخ جوجه کباب ران مرغ با استخوان زعفرانی ۴۵۰ گرمی، ۳۵۰ گرم برنج ایرانی، گوجه کبابی",
    comments: [
      {
        name: "سجاد",
        message: "کباب خیلی کوچیک و کم حجم بود برنج عالی طعم کباب متوسط",
        creationDate: new Date().toLocaleDateString(),
        rate: 4,
        buyProducts: ["جوجه کباب"],
      },
    ],
  },
  {
    id: 8,
    resturantName: "رستوران جوج بار",
    image: "/images/DiscountImage/DiscountFood8.jpeg",
    foodName: "خوراک بال کبابی",
    deliveryPrice: 12000,
    price: 129000,
    discountRange: 40,
    countInStock: 32,
    rate: 3.5,
    foodIngredients:
      "۸ تکه بال مرغ کبابی زعفرانی، گوجه کبابی، دورچین روز، یک عدد نان لواش یا نصف نان سنگک",
    comments: [
      {
        name: "سجاد",
        message: "کباب خیلی کوچیک و کم حجم بود برنج عالی طعم کباب متوسط",
        creationDate: new Date().toLocaleDateString(),
        rate: 4,
        buyProducts: ["جوجه کباب"],
      },
      {
        name: "سجاد",
        message: "کباب خیلی کوچیک و کم حجم بود برنج عالی طعم کباب متوسط",
        creationDate: new Date().toLocaleDateString(),
        rate: 4,
        buyProducts: ["جوجه کباب"],
      },
      {
        name: "سجاد",
        message: "کباب خیلی کوچیک و کم حجم بود برنج عالی طعم کباب متوسط",
        creationDate: new Date().toLocaleDateString(),
        rate: 4,
        buyProducts: ["جوجه کباب"],
      },
    ],
  },
];

export const newExperienceResturantData = [
  {
    id: 1,
    resturantName: "مجنمع نان یاقوت",
    resturantImage: "/images/NewExper/R1.jpg",
    foodImage: "/images/NewExper/RF1.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "ایرانی , سنتی",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4.5,
      usersVotesCount: 231,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 2,
    resturantName: "طباخی آمیرزا",
    resturantImage: "/images/NewExper/R2.jpeg",
    foodImage: "/images/NewExper/RF2.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "ایرانی , سنتی",
    deliveryPrice: 6000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 3,
    resturantName: "کافه دکتر کافی",
    resturantImage: "/images/NewExper/R3.jpeg",
    foodImage: "/images/NewExper/RF3.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "صبحانه,میان وعده,نوشیدنی گرم",
    deliveryPrice: 8000,
    rating: {
      ratingValue: 4.5,
      usersVotesCount: 76,
    },
    freeDeliverByOrder: false,
  },
  {
    id: 4,
    resturantName: "کافه رستوران گفتارخانه",
    resturantImage: "/images/NewExper/R4.jpg",
    foodImage: "/images/NewExper/RF4.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "ایرانی , سنتی",
    deliveryPrice: 16000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 5,
    resturantName: "قنادی هلر",
    resturantImage: "/images/NewExper/R5.jpg",
    foodImage: "/images/NewExper/RF5.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "ایرانی , سنتی",
    deliveryPrice: 6000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 128,
    },
    freeDeliverByOrder: false,
  },
];

export const topRatedData = [
  {
    id: 1,
    resturantName: "پیتزا سیب 360(عباس آباد)",
    resturantImage: "/images/TopRated/R1.png",
    foodImage: "/images/TopRated/RF1.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,برگر",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 2,
    resturantName: "پیتزا پرپروک",
    resturantImage: "/images/TopRated/R2.jpg",
    foodImage: "/images/TopRated/RF2.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "فست فود, پیتزا,سالاد",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: false,
  },
  {
    id: 3,
    resturantName: "پیتزا شیلا",
    resturantImage: "/images/TopRated/R3.jpg",
    foodImage: "/images/TopRated/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,ساندویچ , پیتزا",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 4,
    resturantName: "کافه رستوران گفتارخانه",
    resturantImage: "/images/TopRated/R4.jpg",
    foodImage: "/images/TopRated/RF4.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "کباب ,ایرانی ,سنتی",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
  },
];

export const withDiscountData = [
  {
    id: 1,
    resturantName: "عطاویچ",
    resturantImage: "/images/WDiscount/R1.jpg",
    foodImage: "/images/WDiscount/RF1.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,برگر",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 2,
    resturantName: "فلفل قرمز - قائم مقام",
    resturantImage: "/images/WDiscount/R2.jpeg",
    foodImage: "/images/WDiscount/RF2.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "فست فود, پیتزا,سالاد",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 3,
    resturantName: "مزه پروتئین",
    resturantImage: "/images/WDiscount/R3.jpg",
    foodImage: "/images/WDiscount/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,ساندویچ , پیتزا",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 4,
    resturantName: "هریک",
    resturantImage: "/images/WDiscount/R4.jpg",
    foodImage: "/images/WDiscount/RF4.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,برگر ,مرغ سوخاری",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 5,
    resturantName: "کباب سرای آنیل",
    resturantImage: "/images/AllData/R3.jpg",
    foodImage: "/images/AllData/RF3.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "کباب ,جوجه کباب ,خورشت , چلو",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 180,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: false,
  },
  {
    id: 6,
    resturantName: "کافه شیرینی پراگ (ایرانشهر)",
    resturantImage: "/images/AllData/R4.png",
    foodImage: "/images/AllData/RF4.png",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "نوشیدنی ,قهوه ,اسموتی , شیرینی",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 210,
    },
    freeDeliverByOrder: false,
    category: "کافه",
    discount: true,
    coupun: true,
    expressDelivery: true,
  },
  {
    id: 7,
    resturantName: "کافه رستوران دلوان",
    resturantImage: "/images/AllData/R5.jpeg",
    foodImage: "/images/AllData/RF5.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "نوشیدنی ,ایرانی , ساندویچ",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 220,
    },
    freeDeliverByOrder: true,
    category: "رستوران-کافه",
    discount: true,
    coupun: true,
    expressDelivery: false,
  },
  {
    id: 8,
    resturantName: "آشپزخانه ظفر",
    resturantImage: "/images/AllData/R6.jpg",
    foodImage: "/images/AllData/RF6.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "سنتی ,ایرانی , خورشت",
    deliveryPrice: 0,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 200,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: true,
  },
  {
    id: 9,
    resturantName: "رستوران ارغوان",
    resturantImage: "/images/AllData/R7.png",
    foodImage: "/images/AllData/RF7.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "سنتی ,ایرانی , کباب",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 300,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: false,
  },
];

export const withCouponData = [
  {
    id: 1,
    resturantName: "چیکن فامیلی(یوسف آباد)",
    resturantImage: "/images/WCoupon/R1.jpg",
    foodImage: "/images/WCoupon/RF1.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,چیکن",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 2,
    resturantName: "رستوران روحی",
    resturantImage: "/images/WCoupon/R2.jpg",
    foodImage: "/images/WCoupon/RF2.jpeg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: " کباب, خورشت ,جوجه کباب",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 3,
    resturantName: "ته چین بار",
    resturantImage: "/images/WCoupon/R3.jpg",
    foodImage: "/images/WCoupon/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "ایرانی ,سنتی , ته چین",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4.4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 4,
    resturantName: "فست فود توتو",
    resturantImage: "/images/WCoupon/R4.jpg",
    foodImage: "/images/WCoupon/RF4.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,برگر ,مرغ سوخاری",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
  },
];

export const allResturantData = [
  {
    id: 1,
    resturantName: "چیکن فامیلی(یوسف آباد)",
    resturantImage: "/images/WCoupon/R1.jpg",
    foodImage: "/images/WCoupon/RF1.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,چیکن",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: ["express"],
  },
  {
    id: 2,
    resturantName: "رستوران روحی",
    resturantImage: "/images/WCoupon/R2.jpg",
    foodImage: "/images/WCoupon/RF2.jpeg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: " کباب, خورشت ,جوجه کباب",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["discount", "express", "coupon"],
  },
  {
    id: 3,
    resturantName: "ته چین بار",
    resturantImage: "/images/WCoupon/R3.jpg",
    foodImage: "/images/WCoupon/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "ایرانی ,سنتی , ته چین",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4.4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["express"],
  },
  {
    id: 4,
    resturantName: "فست فود توتو",
    resturantImage: "/images/WCoupon/R4.jpg",
    foodImage: "/images/WCoupon/RF4.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,برگر ,مرغ سوخاری",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: ["discount", "express", "coupon"],
  },
  {
    id: 5,
    resturantName: "چیکن فامیلی(یوسف آباد)",
    resturantImage: "/images/WCoupon/R1.jpg",
    foodImage: "/images/WCoupon/RF1.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,چیکن",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: [],
  },
  {
    id: 6,
    resturantName: "رستوران روحی",
    resturantImage: "/images/WCoupon/R2.jpg",
    foodImage: "/images/WCoupon/RF2.jpeg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: " کباب, خورشت ,جوجه کباب",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["discount"],
  },
  {
    id: 7,
    resturantName: "ته چین بار",
    resturantImage: "/images/WCoupon/R3.jpg",
    foodImage: "/images/WCoupon/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "ایرانی ,سنتی , ته چین",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4.4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["discount", "express", "coupon"],
  },
  {
    id: 8,
    resturantName: "فست فود توتو",
    resturantImage: "/images/WCoupon/R4.jpg",
    foodImage: "/images/WCoupon/RF4.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,برگر ,مرغ سوخاری",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: ["discount", "express", "coupon"],
  },
  {
    id: 9,
    resturantName: "عطاویچ",
    resturantImage: "/images/WDiscount/R1.jpg",
    foodImage: "/images/WDiscount/RF1.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,برگر",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 10,
    resturantName: "فلفل قرمز - قائم مقام",
    resturantImage: "/images/WDiscount/R2.jpeg",
    foodImage: "/images/WDiscount/RF2.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "فست فود, پیتزا,سالاد",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 11,
    resturantName: "مزه پروتئین",
    resturantImage: "/images/WDiscount/R3.jpg",
    foodImage: "/images/WDiscount/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,ساندویچ , پیتزا",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 12,
    resturantName: "هریک",
    resturantImage: "/images/WDiscount/R4.jpg",
    foodImage: "/images/WDiscount/RF4.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,برگر ,مرغ سوخاری",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 13,
    resturantName: "پیتزا سیب 360(عباس آباد)",
    resturantImage: "/images/TopRated/R1.png",
    foodImage: "/images/TopRated/RF1.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,برگر",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 14,
    resturantName: "پیتزا پرپروک",
    resturantImage: "/images/TopRated/R2.jpg",
    foodImage: "/images/TopRated/RF2.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "فست فود, پیتزا,سالاد",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: false,
    category: ["فست فود", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 15,
    resturantName: "پیتزا شیلا",
    resturantImage: "/images/TopRated/R3.jpg",
    foodImage: "/images/TopRated/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,ساندویچ , پیتزا",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 16,
    resturantName: "کافه رستوران گفتارخانه",
    resturantImage: "/images/TopRated/R4.jpg",
    foodImage: "/images/TopRated/RF4.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "کباب ,ایرانی ,سنتی",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["express"],
  },
  {
    id: 17,
    resturantName: "جی کافه",
    resturantImage: "/images/AllData/R1.jpg",
    foodImage: "/images/AllData/RF1.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "صبحانه ,میان وعده ,نوشیدنی",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.3,
      usersVotesCount: 118,
    },
    freeDeliverByOrder: false,
    category: ["کافه", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 18,
    resturantName: "رستوران چهل خانه",
    resturantImage: "/images/AllData/R2.png",
    foodImage: "/images/AllData/RF2.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "صبحانه ,میان وعده ,سنتی, املت",
    deliveryPrice: 19000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 180,
    },
    freeDeliverByOrder: false,
    category: ["کافه", "رستوران"],
    filterBtns: ["express"],
  },
  {
    id: 19,
    resturantName: "کباب سرای آنیل",
    resturantImage: "/images/AllData/R3.jpg",
    foodImage: "/images/AllData/RF3.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "کباب ,جوجه کباب ,خورشت , چلو",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 180,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["express"],
  },
  {
    id: 20,
    resturantName: "کافه شیرینی پراگ (ایرانشهر)",
    resturantImage: "/images/AllData/R4.png",
    foodImage: "/images/AllData/RF4.png",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "نوشیدنی ,قهوه ,اسموتی , شیرینی",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 210,
    },
    freeDeliverByOrder: false,
    category: ["کافه", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 21,
    resturantName: "کافه رستوران دلوان",
    resturantImage: "/images/AllData/R5.jpeg",
    foodImage: "/images/AllData/RF5.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "نوشیدنی ,ایرانی , ساندویچ",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 220,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران", "ایرانی"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 22,
    resturantName: "پیتزا شیلا",
    resturantImage: "/images/TopRated/R3.jpg",
    foodImage: "/images/TopRated/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,ساندویچ , پیتزا",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 23,
    resturantName: "کافه رستوران گفتارخانه",
    resturantImage: "/images/TopRated/R4.jpg",
    foodImage: "/images/TopRated/RF4.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "کباب ,ایرانی ,سنتی",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 24,
    resturantName: "جی کافه",
    resturantImage: "/images/AllData/R1.jpg",
    foodImage: "/images/AllData/RF1.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "صبحانه ,میان وعده ,نوشیدنی",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.3,
      usersVotesCount: 118,
    },
    freeDeliverByOrder: false,
    category: ["کافه", "رستوران"],
    filterBtns: ["express"],
  },
  {
    id: 25,
    resturantName: "رستوران چهل خانه",
    resturantImage: "/images/AllData/R2.png",
    foodImage: "/images/AllData/RF2.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "صبحانه ,میان وعده ,سنتی, املت",
    deliveryPrice: 19000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 180,
    },
    freeDeliverByOrder: false,
    category: ["کافه", "رستوران", "ایرانی"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 26,
    resturantName: "کباب سرای آنیل",
    resturantImage: "/images/AllData/R3.jpg",
    foodImage: "/images/AllData/RF3.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "کباب ,جوجه کباب ,خورشت , چلو",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 180,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 27,
    resturantName: "کافه شیرینی پراگ (ایرانشهر)",
    resturantImage: "/images/AllData/R4.png",
    foodImage: "/images/AllData/RF4.png",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "نوشیدنی ,قهوه ,اسموتی , شیرینی",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 210,
    },
    freeDeliverByOrder: false,
    category: ["کافه", "رستوران", "شیرینی"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 28,
    resturantName: "کافه رستوران دلوان",
    resturantImage: "/images/AllData/R5.jpeg",
    foodImage: "/images/AllData/RF5.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "نوشیدنی ,ایرانی , ساندویچ",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 220,
    },
    freeDeliverByOrder: true,
    category: ["کافه", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 29,
    resturantName: "آشپزخانه ظفر",
    resturantImage: "/images/AllData/R6.jpg",
    foodImage: "/images/AllData/RF6.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "سنتی ,ایرانی , خورشت",
    deliveryPrice: 0,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 200,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["express"],
  },
  {
    id: 30,
    resturantName: "رستوران ارغوان",
    resturantImage: "/images/AllData/R7.png",
    foodImage: "/images/AllData/RF7.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "سنتی ,ایرانی , کباب",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 300,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["express"],
  },
  {
    id: 31,
    resturantName: "کترینگ سیب",
    resturantImage: "/images/AllData/R8.jpg",
    foodImage: "/images/AllData/RF8.png",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "سنتی ,ایرانی , کباب",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 300,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 32,
    resturantName: "نان و شیرینی جم",
    resturantImage: "/images/AllData/R9.jpeg",
    foodImage: "/images/AllData/RF9.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "شیرینی ,نان , کیک",
    deliveryPrice: 24000,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 200,
    },
    freeDeliverByOrder: true,
    category: ["شیرینی"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 33,
    resturantName: "قنادی توکلی فر تبریزی",
    resturantImage: "/images/AllData/R10.jpg",
    foodImage: "/images/AllData/RF10.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "شیرینی ,نان , کیک",
    deliveryPrice: 14000,
    rating: {
      ratingValue: 3.8,
      usersVotesCount: 270,
    },
    freeDeliverByOrder: false,
    category: ["شیرینی"],
    filterBtns: ["express"],
  },
  {
    id: 34,
    resturantName: "شیرینی سهروردی",
    resturantImage: "/images/AllData/R11.jpg",
    foodImage: "/images/AllData/RF11.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "شیرینی ,نان , کیک",
    deliveryPrice: 14000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 270,
    },
    freeDeliverByOrder: false,
    category: ["شیرینی"],
    filterBtns: ["express"],
  },
  {
    id: 35,
    resturantName: "شیرینی تینا",
    resturantImage: "/images/AllData/R12.jpg",
    foodImage: "/images/AllData/RF12.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "شیرینی ,نان , کیک",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
    category: ["شیرینی"],
    filterBtns: ["express"],
  },
];

export const sideBarData = [
  {
    id: 1,
    categoryName: "غذا",
    categoryImage: "/images/SideBar/IM1.png",
  },
  {
    id: 2,
    categoryName: "نوشیدنی گرم",
    categoryImage: "/images/SideBar/IM2.png",
  },
  {
    id: 3,
    categoryName: "نوشیدنی سرد",
    categoryImage: "/images/SideBar/IM3.png",
  },
  {
    id: 4,
    categoryName: "کیک و دسر",
    categoryImage: "/images/SideBar/IM4.png",
  },
  {
    id: 5,
    categoryName: "بستنی",
    categoryImage: "/images/SideBar/IM5.png",
  },
];
