export const bannerCategoryData = [
  {
    id: 1,
    imagePath: "/images/Category-img1.png",
    title: "پروتِین",
    routesName: "meats",
  },
  {
    id: 2,
    imagePath: "/images/Category-img2.png",
    title: "آبمیوه بستنی",
    routesName: "icecreams",
  },
  {
    id: 3,
    imagePath: "/images/Category-img3.png",
    title: "آجیل",
    routesName: "nuts",
  },
  {
    id: 4,
    imagePath: "/images/Category-img4.png",
    title: "سایر",
    routesName: "other",
  },
  {
    id: 5,
    imagePath: "/images/Category-img5.png",
    title: "میوه",
    routesName: "fruits",
  },
  {
    id: 6,
    imagePath: "/images/Category-img6.png",
    title: "نانوایی",
    routesName: "breads",
  },
  {
    id: 7,
    imagePath: "/images/Category-img7.png",
    title: "شیرینی",
    routesName: "cookies",
  },
  {
    id: 8,
    imagePath: "/images/Category-img8.png",
    title: "کافه",
    routesName: "cafe",
  },
  {
    id: 9,
    imagePath: "/images/Category-img9.png",
    title: "سوپرمارکت",
    routesName: "supermarket",
  },
  {
    id: 10,
    imagePath: "/images/Category-img10.png",
    title: "رستوران",
    routesName: "resturant",
  },
];

export const foodCategoryData = [
  {
    categoryId: 1,
    name: "ایرانی",
    routName: "irani",
    categoryImage: "/images/Cimage/R1.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی"],
      },
      {
        Id: 2,
        title: "چلوپز سهروردی",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 2,
    name: "فست فود",
    routName: "fast-food",
    categoryImage: "/images/Cimage/R2.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 3,
    name: "کباب",
    routName: "kabab",
    categoryImage: "/images/Cimage/R3.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 4,
    name: "پیتزا",
    routName: "pitza",
    categoryImage: "/images/Cimage/R4.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 5,
    name: "برگر",
    routName: "berger",
    categoryImage: "/images/Cimage/R5.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 6,
    name: "ساندویچ",
    routName: "sandwich",
    categoryImage: "/images/Cimage/R6.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 7,
    name: "سوخاری",
    routName: "sokhari",
    categoryImage: "/images/Cimage/R7.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 8,
    name: "پاستا",
    routName: "pasta",
    categoryImage: "/images/Cimage/R8.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 9,
    name: "سالاد",
    routName: "salad",
    categoryImage: "/images/Cimage/R9.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 10,
    name: "دریایی",
    routName: "sea",
    categoryImage: "/images/Cimage/R10.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 11,
    name: "بین الملل",
    routName: "international",
    categoryImage: "/images/Cimage/R11.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 12,
    name: "گیلانی",
    routName: "gilani",
    categoryImage: "/images/Cimage/R12.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
];
export const DiscountData = [
  {
    id: 1,
    resturantName: "پیتزا هات سهروردی",
    image: "/images/DiscountImage/DiscountFood1.jpeg",
    foodName: "پیتزا سالامی آمریکایی دو نفره (۳۰ سانتی متری)",
    deliveryPrice: 15000,
    price: 100000,
    discountRange: 30,
    countInStock: 82,
    rate: 3.5,
    foodIngredients: "خمیر پیتزا آمریکایی، سالامی، قارچ، پنیر پارمسان",
    comments: [
      {
        name: "سجاد",
        message: "کباب خیلی کوچیک و کم حجم بود برنج عالی طعم کباب متوسط",
        creationDate: new Date().toLocaleDateString(),
        rate: 4,
        buyProducts: ["جوجه کباب"],
      },
    ],
  },
  {
    id: 2,
    resturantName: "پیزاریوم",
    image: "/images/DiscountImage/DiscountFood2.jpeg",
    foodName: "پیتزا سوپریم (ایتالیایی) دو نفره (۳۰ سانتی متری)",
    deliveryPrice: 15000,
    price: 120000,
    discountRange: 40,
    countInStock: 62,
    rate: 3.9,
    foodIngredients:
      "خمیر پیتزا ایتالیایی، ژامبون گوشت و مرغ، سس مخصوص، زیتون اسلایسی، فلفل دلمه ای، ذرت، پنیر مخصوص، سس تک نفره",
    comments: [
      {
        name: "سجاد",
        message: "کباب خیلی کوچیک و کم حجم بود برنج عالی طعم کباب متوسط",
        creationDate: new Date().toLocaleDateString(),
        rate: 4,
        buyProducts: ["جوجه کباب"],
      },
    ],
  },
  {
    id: 3,
    resturantName: "رستوران مانی",
    image: "/images/DiscountImage/DiscountFood3.jpeg",
    foodName: "چلو کباب لقمه مخصوص",
    deliveryPrice: 15000,
    price: 220000,
    discountRange: 20,
    countInStock: 32,
    rate: 4.5,
    foodIngredients: "۲۰۰ گرم گوشت گوسفندی، برنج ایرانی، مخلفات",
    comments: [
      {
        name: "سجاد",
        message: "کباب خیلی کوچیک و کم حجم بود برنج عالی طعم کباب متوسط",
        creationDate: new Date().toLocaleDateString(),
        rate: 4,
        buyProducts: ["جوجه کباب"],
      },
    ],
  },
  {
    id: 4,
    resturantName: "ته چین بار (مطهری)",
    image: "/images/DiscountImage/DiscountFood4.jpeg",
    foodName: "ته چین باقالی پلو با ماهیچه",
    deliveryPrice: 17000,
    price: 220000,
    discountRange: 20,
    countInStock: 62,
    rate: 3.5,
    foodIngredients:
      "۱۱۰ گرم ماهیچه گوساله، ۳۵۰ گرم ته چین باقالی پلو قالبی با برنج ایرانی",
    comments: [
      {
        name: "سجاد",
        message: "کباب خیلی کوچیک و کم حجم بود برنج عالی طعم کباب متوسط",
        creationDate: new Date().toLocaleDateString(),
        rate: 4,
        buyProducts: ["جوجه کباب"],
      },
    ],
  },
  {
    id: 5,
    resturantName: "پیتزا شیلا (هفت تیر)",
    image: "/images/DiscountImage/DiscountFood6.jpeg",
    foodName: "پیتزا مخلوط (۲۳ سانتی‌ متری)",
    deliveryPrice: 12000,
    price: 170000,
    discountRange: 40,
    countInStock: 42,
    rate: 4.5,
    foodIngredients:
      "خمیر پیتزا کلاسیک ۲۳ سانتی‌ متری، ژامبون گوشت و مرغ، هات داگ فرانکفورتر، قارچ، زیتون، گوجه فرنگی، فلفل دلمه‌ ای",
    comments: [
      {
        name: "سجاد",
        message: "کباب خیلی کوچیک و کم حجم بود برنج عالی طعم کباب متوسط",
        creationDate: new Date().toLocaleDateString(),
        rate: 4,
        buyProducts: ["جوجه کباب"],
      },
    ],
  },
  {
    id: 6,
    resturantName: "ژیرا",
    image: "/images/DiscountImage/DiscountFood7.jpeg",
    foodName: "برگر ویژه ژیرا",
    deliveryPrice: 15000,
    price: 90000,
    discountRange: 30,
    countInStock: 112,
    rate: 4.5,
    foodIngredients:
      "یک عدد برگر دست ساز گوشت گوساله ۲۲۰ گرمی، فیله مرغ، بیکن ۸۰%، پنیر گودا و قارچ، نان گرد",
    comments: [
      {
        name: "سجاد",
        message: "کباب خیلی کوچیک و کم حجم بود برنج عالی طعم کباب متوسط",
        creationDate: new Date().toLocaleDateString(),
        rate: 4,
        buyProducts: ["جوجه کباب"],
      },
    ],
  },
  {
    id: 7,
    resturantName: "رستوران جوج بار",
    image: "/images/DiscountImage/DiscountFood5.jpeg",
    foodName: "چلو جوجه کباب استخوانی زعفرانی",
    deliveryPrice: 15000,
    price: 121000,
    discountRange: 40,
    countInStock: 72,
    rate: 4.5,
    foodIngredients:
      "یک سیخ جوجه کباب ران مرغ با استخوان زعفرانی ۴۵۰ گرمی، ۳۵۰ گرم برنج ایرانی، گوجه کبابی",
    comments: [
      {
        name: "سجاد",
        message: "کباب خیلی کوچیک و کم حجم بود برنج عالی طعم کباب متوسط",
        creationDate: new Date().toLocaleDateString(),
        rate: 4,
        buyProducts: ["جوجه کباب"],
      },
    ],
  },
  {
    id: 8,
    resturantName: "رستوران جوج بار",
    image: "/images/DiscountImage/DiscountFood8.jpeg",
    foodName: "خوراک بال کبابی",
    deliveryPrice: 12000,
    price: 129000,
    discountRange: 40,
    countInStock: 32,
    rate: 3.5,
    foodIngredients:
      "۸ تکه بال مرغ کبابی زعفرانی، گوجه کبابی، دورچین روز، یک عدد نان لواش یا نصف نان سنگک",
    comments: [
      {
        name: "سجاد",
        message: "کباب خیلی کوچیک و کم حجم بود برنج عالی طعم کباب متوسط",
        creationDate: new Date().toLocaleDateString(),
        rate: 4,
        buyProducts: ["جوجه کباب"],
      },
      {
        name: "سجاد",
        message: "کباب خیلی کوچیک و کم حجم بود برنج عالی طعم کباب متوسط",
        creationDate: new Date().toLocaleDateString(),
        rate: 4,
        buyProducts: ["جوجه کباب"],
      },
      {
        name: "سجاد",
        message: "کباب خیلی کوچیک و کم حجم بود برنج عالی طعم کباب متوسط",
        creationDate: new Date().toLocaleDateString(),
        rate: 4,
        buyProducts: ["جوجه کباب"],
      },
    ],
  },
];

export const newExperienceResturantData = [
  {
    id: 1,
    resturantName: "مجنمع نان یاقوت",
    resturantImage: "/images/NewExper/R1.jpg",
    foodImage: "/images/NewExper/RF1.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "ایرانی , سنتی",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4.5,
      usersVotesCount: 231,
    },
    freeDeliverByOrder: true,
    routName: "newexperiences",
    coupons: [
      "ارسال رایگان با سفارش حداقل 300 هزار تومن",
      "5 درصد تخفیف مخصوص سفارش اول",
    ],
    products: [
      {
        title: "سنگک سنتی دو رو پر کنجد بزرگ",
        ingredients: "نان سنگک سبوس دار",
        inStock: 20,
        image: "/images/NewExper/F6.jpeg",
        price: 50000,
      },
      {
        title: "گاتا مغز دار گردو و خرما",
        ingredients: "تشکیل شده از: مغزی مخصوص با گردو",
        inStock: 10,
        image: "/images/NewExper/F6.jpeg",
        price: 23000,
      },
      {
        title: "گاتا کره ای",
        ingredients: "تشکیل شده از: مغزی مخصوص",
        inStock: 30,
        image: "/images/NewExper/F7.jpeg",
        price: 30000,
      },
      {
        title: "نان کارامل شکلات",
        ingredients: "تشکیل شده از: کارامل و شکلات",
        inStock: 10,
        image: "/images/NewExper/F8.jpeg",
        price: 40000,
      },
      {
        title: "نان  شیرمال گرد",
        ingredients: "تشکیل شده از: کارامل و شکلات",
        inStock: 10,
        image: "/images/NewExper/F11.jpeg",
        price: 30000,
      },
    ],
    drinks: [],
  },
  {
    id: 2,
    resturantName: "طباخی آمیرزا",
    resturantImage: "/images/NewExper/R2.jpeg",
    foodImage: "/images/NewExper/RF2.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "ایرانی , سنتی",
    deliveryPrice: 6000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: true,
    routName: "newexperiences",
    coupons: [
      "ارسال رایگان با سفارش حداقل 300 هزار تومن",
      "5 درصد تخفیف مخصوص سفارش اول",
    ],
    products: [
      {
        id: 1,
        title: "پاچه",
        ingredients: "یک عدد پاچه به همراه نان سنگک و نارنج",
        inStock: 20,
        image: "/images/NewExper/F2.jpeg",
        price: 200000,
      },
      {
        id: 2,
        title: "زبان",
        ingredients: "یک عدد زبان به همراه نان سنگک و نارنج",
        inStock: 20,
        image: "/images/NewExper/F1.jpeg",
        price: 290000,
      },
      {
        id: 3,
        title: "سینی یک نفره",
        ingredients:
          "یک عدد بناگوش، یک عدد پاچه، نصف مغز، یک عدد چشم، به همراه نان سنگک و نارنج",
        inStock: 30,
        image: "/images/NewExper/F3.jpeg",
        price: 210000,
      },
      {
        id: 4,
        title: "سینی دو نفره",
        ingredients:
          "دو عدد بنا گوش، یک عدد زبان، یک جفت پاچه، یک عدد مغز کامل، یک جفت چشم، به همراه نان سنگک و نارنج",
        inStock: 10,
        image: "/images/NewExper/F1.jpeg",
        price: 150000,
      },
      {
        id: 5,
        title: "کل پاچه یک دست کامل",
        ingredients:
          "(مناسب برای ۳-۴ نفر)، یک عدد زبان، یک عدد مغز، دو عدد بناگوش، یک پرس گوشت لخم، یک جفت چشم، ۴ عدد پاچه، آب گوشت، به همراه نان سنگک و نارنج",
        inStock: 10,
        image: "/images/NewExper/F1.jpeg",
        price: 180000,
      },
      {
        id: 5,
        title: "آب گوشت",
        ingredients:
          "(مناسب برای ۳-۴ نفر)، یک عدد زبان، یک عدد مغز، دو عدد بناگوش، یک پرس گوشت لخم، یک جفت چشم، ۴ عدد پاچه، آب گوشت، به همراه نان سنگک و نارنج",
        inStock: 10,
        image: "/images/NewExper/F4.jpeg",
        price: 280000,
      },
    ],
    drinks: [
      {
        id: 1,
        title: "لیموناد شیشه ای",
        image: "/images/Drinks/D2.jpg",
      },
      {
        id: 2,
        title: "نوشابه شیشه ای",
        image: "/images/Drinks/D1.jpg",
      },
      {
        id: 3,
        title: "نوشابه قوطی کوکاکولا",
        image: "/images/Drinks/D3.jpg",
      },
      {
        id: 4,
        title: "نوشابه قوطی پرتغالی",
        image: "/images/Drinks/D4.jpg",
      },
      {
        id: 5,
        title: "نوشابه قوطی سون آپ",
        image: "/images/Drinks/D5.jpg",
      },
    ],
  },
  {
    id: 3,
    resturantName: "کافه دکتر کافی",
    resturantImage: "/images/NewExper/R3.jpeg",
    foodImage: "/images/NewExper/RF3.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "صبحانه,میان وعده,نوشیدنی گرم",
    deliveryPrice: 8000,
    rating: {
      ratingValue: 4.5,
      usersVotesCount: 76,
    },
    coupons: [
      "ارسال رایگان با سفارش حداقل 300 هزار تومن",
      "5 درصد تخفیف مخصوص سفارش اول",
    ],
    freeDeliverByOrder: false,
    routName: "newexperiences",
    products: [
      {
        id: 1,
        title: "لانگو",
        ingredients: "۳۶۰ میلی لیتر، اسپرسو دبل، آب ۹۱ درجه",
        inStock: 20,
        image: "/images/Cafe/C1.jpeg",
        price: 100000,
      },
      {
        id: 2,
        title: "اسپرسو عربیکا",
        ingredients: "۳۶۰ میلی لیتر، اسپرسو دبل، آب ۹۱ درجه",
        inStock: 20,
        image: "/images/Cafe/C2.jpeg",
        price: 100000,
      },
      {
        id: 3,
        title: "لاته",
        ingredients: "۳۶۰ میلی لیتر، اسپرسو دبل، آب ۹۱ درجه",
        inStock: 20,
        image: "/images/Cafe/C3.jpeg",
        price: 100000,
      },
      {
        id: 4,
        title: "قهوه آمریکانو",
        ingredients: "۳۶۰ میلی لیتر، اسپرسو دبل، آب ۹۱ درجه",
        inStock: 20,
        image: "/images/Cafe/C4.jpeg",
        price: 100000,
      },
      {
        id: 5,
        title: "کاپوچینو",
        ingredients: "۳۶۰ میلی لیتر، اسپرسو دبل، آب ۹۱ درجه",
        inStock: 20,
        image: "/images/Cafe/C5.jpeg",
        price: 100000,
      },
      {
        id: 6,
        title: "قهوه فرانسه",
        ingredients: "۳۶۰ میلی لیتر، اسپرسو دبل، آب ۹۱ درجه",
        inStock: 20,
        image: "/images/Cafe/C1.jpeg",
        price: 100000,
      },
      {
        id: 7,
        title: "فلت وایت",
        ingredients: "۳۶۰ میلی لیتر، اسپرسو دبل، آب ۹۱ درجه",
        inStock: 20,
        image: "/images/Cafe/C3.jpeg",
        price: 100000,
      },
      {
        id: 8,
        title: "شیرنسکافه",
        ingredients: "۳۶۰ میلی لیتر، اسپرسو دبل، آب ۹۱ درجه",
        inStock: 20,
        image: "/images/Cafe/C5.jpeg",
        price: 100000,
      },
      {
        id: 9,
        title: "شیرقهوه",
        ingredients: "۳۶۰ میلی لیتر، اسپرسو دبل، آب ۹۱ درجه",
        inStock: 20,
        image: "/images/Cafe/C6.jpeg",
        price: 100000,
      },
      {
        id: 10,
        title: "هات چاکلت کلاسیک",
        ingredients: "۳۶۰ میلی لیتر، اسپرسو دبل، آب ۹۱ درجه",
        inStock: 20,
        image: "/images/Cafe/C8.jpeg",
        price: 100000,
      },
      {
        id: 10,
        title: "چای",
        ingredients: "۳۶۰ میلی لیتر، اسپرسو دبل، آب ۹۱ درجه",
        inStock: 20,
        image: "/images/Cafe/T1.jpeg",
        price: 100000,
      },
    ],
    drinks: [
      {
        id: 1,
        title: "لیموناد شیشه ای",
        image: "/images/Drinks/D2.jpg",
      },
      {
        id: 2,
        title: "نوشابه شیشه ای",
        image: "/images/Drinks/D1.jpg",
      },
      {
        id: 3,
        title: "نوشابه قوطی کوکاکولا",
        image: "/images/Drinks/D3.jpg",
      },
      {
        id: 4,
        title: "نوشابه قوطی پرتغالی",
        image: "/images/Drinks/D4.jpg",
      },
      {
        id: 5,
        title: "نوشابه قوطی سون آپ",
        image: "/images/Drinks/D5.jpg",
      },
    ],
  },
  // {
  //   id: 4,
  //   resturantName: "کافه رستوران گفتارخانه",
  //   resturantImage: "/images/NewExper/R4.jpg",
  //   foodImage: "/images/NewExper/RF4.jpg",
  //   deliveryType: "ارسال اکسپرس",
  //   shortDescription: "ایرانی , سنتی",
  //   deliveryPrice: 16000,
  //   rating: {
  //     ratingValue: 4.2,
  //     usersVotesCount: 168,
  //   },
  //   freeDeliverByOrder: true,
  //   routName: "",
  // },
  // {
  //   id: 5,
  //   resturantName: "قنادی هلر",
  //   resturantImage: "/images/NewExper/R5.jpg",
  //   foodImage: "/images/NewExper/RF5.jpg",
  //   deliveryType: "ارسال اکسپرس",
  //   shortDescription: "ایرانی , سنتی",
  //   deliveryPrice: 6000,
  //   rating: {
  //     ratingValue: 4.2,
  //     usersVotesCount: 128,
  //   },
  //   freeDeliverByOrder: false,
  //   routName: "goftarkhane",
  // },
];

export const topRatedData = [
  {
    id: 1,
    resturantName: "پیتزا سیب 360(عباس آباد)",
    resturantImage: "/images/TopRated/R1.png",
    foodImage: "/images/TopRated/RF1.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,برگر",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 2,
    resturantName: "پیتزا پرپروک",
    resturantImage: "/images/TopRated/R2.jpg",
    foodImage: "/images/TopRated/RF2.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "فست فود, پیتزا,سالاد",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: false,
  },
  {
    id: 3,
    resturantName: "پیتزا شیلا",
    resturantImage: "/images/TopRated/R3.jpg",
    foodImage: "/images/TopRated/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,ساندویچ , پیتزا",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 4,
    resturantName: "کافه رستوران گفتارخانه",
    resturantImage: "/images/TopRated/R4.jpg",
    foodImage: "/images/TopRated/RF4.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "کباب ,ایرانی ,سنتی",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
  },
];

export const withDiscountData = [
  {
    id: 1,
    resturantName: "عطاویچ",
    resturantImage: "/images/WDiscount/R1.jpg",
    foodImage: "/images/WDiscount/RF1.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,برگر",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 2,
    resturantName: "فلفل قرمز - قائم مقام",
    resturantImage: "/images/WDiscount/R2.jpeg",
    foodImage: "/images/WDiscount/RF2.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "فست فود, پیتزا,سالاد",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 3,
    resturantName: "مزه پروتئین",
    resturantImage: "/images/WDiscount/R3.jpg",
    foodImage: "/images/WDiscount/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,ساندویچ , پیتزا",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 4,
    resturantName: "هریک",
    resturantImage: "/images/WDiscount/R4.jpg",
    foodImage: "/images/WDiscount/RF4.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,برگر ,مرغ سوخاری",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 5,
    resturantName: "کباب سرای آنیل",
    resturantImage: "/images/AllData/R3.jpg",
    foodImage: "/images/AllData/RF3.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "کباب ,جوجه کباب ,خورشت , چلو",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 180,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: false,
  },
  {
    id: 6,
    resturantName: "کافه شیرینی پراگ (ایرانشهر)",
    resturantImage: "/images/AllData/R4.png",
    foodImage: "/images/AllData/RF4.png",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "نوشیدنی ,قهوه ,اسموتی , شیرینی",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 210,
    },
    freeDeliverByOrder: false,
    category: "کافه",
    discount: true,
    coupun: true,
    expressDelivery: true,
  },
  {
    id: 7,
    resturantName: "کافه رستوران دلوان",
    resturantImage: "/images/AllData/R5.jpeg",
    foodImage: "/images/AllData/RF5.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "نوشیدنی ,ایرانی , ساندویچ",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 220,
    },
    freeDeliverByOrder: true,
    category: "رستوران-کافه",
    discount: true,
    coupun: true,
    expressDelivery: false,
  },
  {
    id: 8,
    resturantName: "آشپزخانه ظفر",
    resturantImage: "/images/AllData/R6.jpg",
    foodImage: "/images/AllData/RF6.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "سنتی ,ایرانی , خورشت",
    deliveryPrice: 0,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 200,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: true,
  },
  {
    id: 9,
    resturantName: "رستوران ارغوان",
    resturantImage: "/images/AllData/R7.png",
    foodImage: "/images/AllData/RF7.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "سنتی ,ایرانی , کباب",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 300,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: false,
  },
];

export const withCouponData = [
  {
    id: 1,
    resturantName: "چیکن فامیلی(یوسف آباد)",
    resturantImage: "/images/WCoupon/R1.jpg",
    foodImage: "/images/WCoupon/RF1.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,چیکن",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 2,
    resturantName: "رستوران روحی",
    resturantImage: "/images/WCoupon/R2.jpg",
    foodImage: "/images/WCoupon/RF2.jpeg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: " کباب, خورشت ,جوجه کباب",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 3,
    resturantName: "ته چین بار",
    resturantImage: "/images/WCoupon/R3.jpg",
    foodImage: "/images/WCoupon/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "ایرانی ,سنتی , ته چین",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4.4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 4,
    resturantName: "فست فود توتو",
    resturantImage: "/images/WCoupon/R4.jpg",
    foodImage: "/images/WCoupon/RF4.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,برگر ,مرغ سوخاری",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
  },
];

export const allResturantData = [
  {
    id: 1,
    resturantName: "چیکن فامیلی(یوسف آباد)",
    resturantImage: "/images/WCoupon/R1.jpg",
    foodImage: "/images/WCoupon/RF1.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,چیکن",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: ["express"],
  },
  {
    id: 2,
    resturantName: "رستوران روحی",
    resturantImage: "/images/WCoupon/R2.jpg",
    foodImage: "/images/WCoupon/RF2.jpeg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: " کباب, خورشت ,جوجه کباب",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["discount", "express", "coupon"],
  },
  {
    id: 3,
    resturantName: "ته چین بار",
    resturantImage: "/images/WCoupon/R3.jpg",
    foodImage: "/images/WCoupon/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "ایرانی ,سنتی , ته چین",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4.4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["express"],
  },
  {
    id: 4,
    resturantName: "فست فود توتو",
    resturantImage: "/images/WCoupon/R4.jpg",
    foodImage: "/images/WCoupon/RF4.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,برگر ,مرغ سوخاری",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: ["discount", "express", "coupon"],
  },
  {
    id: 5,
    resturantName: "چیکن فامیلی(یوسف آباد)",
    resturantImage: "/images/WCoupon/R1.jpg",
    foodImage: "/images/WCoupon/RF1.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,چیکن",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: [],
  },
  {
    id: 6,
    resturantName: "رستوران روحی",
    resturantImage: "/images/WCoupon/R2.jpg",
    foodImage: "/images/WCoupon/RF2.jpeg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: " کباب, خورشت ,جوجه کباب",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["discount"],
  },
  {
    id: 7,
    resturantName: "ته چین بار",
    resturantImage: "/images/WCoupon/R3.jpg",
    foodImage: "/images/WCoupon/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "ایرانی ,سنتی , ته چین",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4.4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["discount", "express", "coupon"],
  },
  {
    id: 8,
    resturantName: "فست فود توتو",
    resturantImage: "/images/WCoupon/R4.jpg",
    foodImage: "/images/WCoupon/RF4.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,برگر ,مرغ سوخاری",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: ["discount", "express", "coupon"],
  },
  {
    id: 9,
    resturantName: "عطاویچ",
    resturantImage: "/images/WDiscount/R1.jpg",
    foodImage: "/images/WDiscount/RF1.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,برگر",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 10,
    resturantName: "فلفل قرمز - قائم مقام",
    resturantImage: "/images/WDiscount/R2.jpeg",
    foodImage: "/images/WDiscount/RF2.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "فست فود, پیتزا,سالاد",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 11,
    resturantName: "مزه پروتئین",
    resturantImage: "/images/WDiscount/R3.jpg",
    foodImage: "/images/WDiscount/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,ساندویچ , پیتزا",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 12,
    resturantName: "هریک",
    resturantImage: "/images/WDiscount/R4.jpg",
    foodImage: "/images/WDiscount/RF4.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,برگر ,مرغ سوخاری",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 13,
    resturantName: "پیتزا سیب 360(عباس آباد)",
    resturantImage: "/images/TopRated/R1.png",
    foodImage: "/images/TopRated/RF1.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,برگر",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 14,
    resturantName: "پیتزا پرپروک",
    resturantImage: "/images/TopRated/R2.jpg",
    foodImage: "/images/TopRated/RF2.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "فست فود, پیتزا,سالاد",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: false,
    category: ["فست فود", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 15,
    resturantName: "پیتزا شیلا",
    resturantImage: "/images/TopRated/R3.jpg",
    foodImage: "/images/TopRated/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,ساندویچ , پیتزا",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 16,
    resturantName: "کافه رستوران گفتارخانه",
    resturantImage: "/images/TopRated/R4.jpg",
    foodImage: "/images/TopRated/RF4.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "کباب ,ایرانی ,سنتی",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["express"],
  },
  {
    id: 17,
    resturantName: "جی کافه",
    resturantImage: "/images/AllData/R1.jpg",
    foodImage: "/images/AllData/RF1.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "صبحانه ,میان وعده ,نوشیدنی",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.3,
      usersVotesCount: 118,
    },
    freeDeliverByOrder: false,
    category: ["کافه", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 18,
    resturantName: "رستوران چهل خانه",
    resturantImage: "/images/AllData/R2.png",
    foodImage: "/images/AllData/RF2.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "صبحانه ,میان وعده ,سنتی, املت",
    deliveryPrice: 19000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 180,
    },
    freeDeliverByOrder: false,
    category: ["کافه", "رستوران"],
    filterBtns: ["express"],
  },
  {
    id: 19,
    resturantName: "کباب سرای آنیل",
    resturantImage: "/images/AllData/R3.jpg",
    foodImage: "/images/AllData/RF3.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "کباب ,جوجه کباب ,خورشت , چلو",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 180,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["express"],
  },
  {
    id: 20,
    resturantName: "کافه شیرینی پراگ (ایرانشهر)",
    resturantImage: "/images/AllData/R4.png",
    foodImage: "/images/AllData/RF4.png",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "نوشیدنی ,قهوه ,اسموتی , شیرینی",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 210,
    },
    freeDeliverByOrder: false,
    category: ["کافه", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 21,
    resturantName: "کافه رستوران دلوان",
    resturantImage: "/images/AllData/R5.jpeg",
    foodImage: "/images/AllData/RF5.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "نوشیدنی ,ایرانی , ساندویچ",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 220,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران", "ایرانی"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 22,
    resturantName: "پیتزا شیلا",
    resturantImage: "/images/TopRated/R3.jpg",
    foodImage: "/images/TopRated/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,ساندویچ , پیتزا",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
    category: ["فست فود", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 23,
    resturantName: "کافه رستوران گفتارخانه",
    resturantImage: "/images/TopRated/R4.jpg",
    foodImage: "/images/TopRated/RF4.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "کباب ,ایرانی ,سنتی",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 24,
    resturantName: "جی کافه",
    resturantImage: "/images/AllData/R1.jpg",
    foodImage: "/images/AllData/RF1.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "صبحانه ,میان وعده ,نوشیدنی",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.3,
      usersVotesCount: 118,
    },
    freeDeliverByOrder: false,
    category: ["کافه", "رستوران"],
    filterBtns: ["express"],
  },
  {
    id: 25,
    resturantName: "امیر شکلات",
    resturantImage: "/images/AllData/R31.png",
    foodImage: "/images/AllData/RF31.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "صبحانه ,میان وعده ,شکلات, قهوه",
    deliveryPrice: 19000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 180,
    },
    freeDeliverByOrder: false,
    category: ["کافه", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 26,
    resturantName: "کباب سرای آنیل",
    resturantImage: "/images/AllData/R3.jpg",
    foodImage: "/images/AllData/RF3.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "کباب ,جوجه کباب ,خورشت , چلو",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 180,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 27,
    resturantName: "کافه-بار ژوزک(آپادانا)",
    resturantImage: "/images/AllData/R32.png",
    foodImage: "/images/AllData/RF32.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "نوشیدنی ,قهوه ,اسموتی , شیرینی",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 210,
    },
    freeDeliverByOrder: false,
    category: ["کافه", "رستوران", "شیرینی"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 28,
    resturantName: "کافه رستوران دلوان",
    resturantImage: "/images/AllData/R5.jpeg",
    foodImage: "/images/AllData/RF5.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "نوشیدنی ,ایرانی , ساندویچ",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 220,
    },
    freeDeliverByOrder: true,
    category: ["کافه", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 29,
    resturantName: "آشپزخانه ظفر",
    resturantImage: "/images/AllData/R6.jpg",
    foodImage: "/images/AllData/RF6.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "سنتی ,ایرانی , خورشت",
    deliveryPrice: 0,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 200,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["express"],
  },
  {
    id: 30,
    resturantName: "رستوران ارغوان",
    resturantImage: "/images/AllData/R7.png",
    foodImage: "/images/AllData/RF7.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "سنتی ,ایرانی , کباب",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 300,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["express"],
  },
  {
    id: 31,
    resturantName: "کترینگ سیب",
    resturantImage: "/images/AllData/R8.jpg",
    foodImage: "/images/AllData/RF8.png",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "سنتی ,ایرانی , کباب",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 300,
    },
    freeDeliverByOrder: true,
    category: ["ایرانی", "رستوران"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 32,
    resturantName: "نان و شیرینی جم",
    resturantImage: "/images/AllData/R9.jpeg",
    foodImage: "/images/AllData/RF9.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "شیرینی ,نان , کیک",
    deliveryPrice: 24000,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 200,
    },
    freeDeliverByOrder: true,
    category: ["شیرینی", "نانوایی"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 33,
    resturantName: "قنادی توکلی فر تبریزی",
    resturantImage: "/images/AllData/R10.jpg",
    foodImage: "/images/AllData/RF10.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "شیرینی ,نان , کیک",
    deliveryPrice: 14000,
    rating: {
      ratingValue: 3.8,
      usersVotesCount: 270,
    },
    freeDeliverByOrder: false,
    category: ["شیرینی", "نانوایی"],
    filterBtns: ["express"],
  },
  {
    id: 34,
    resturantName: "شیرینی سهروردی",
    resturantImage: "/images/AllData/R11.jpg",
    foodImage: "/images/AllData/RF11.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "شیرینی ,نان , کیک",
    deliveryPrice: 14000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 270,
    },
    freeDeliverByOrder: false,
    category: ["شیرینی", "نانوایی"],
    filterBtns: ["express"],
  },
  {
    id: 35,
    resturantName: "شیرینی تینا",
    resturantImage: "/images/AllData/R12.jpg",
    foodImage: "/images/AllData/RF12.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "شیرینی ,نان , کیک",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
    category: ["شیرینی"],
    filterBtns: ["express"],
  },
  {
    id: 36,
    resturantName: "نان سحر",
    resturantImage: "/images/AllData/R13.jpg",
    foodImage: "/images/AllData/RF13.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "شیرینی ,نان , کیک",
    deliveryPrice: 16000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 370,
    },
    freeDeliverByOrder: true,
    category: ["شیرینی", "نانوایی"],
    filterBtns: ["express"],
  },
  {
    id: 37,
    resturantName: "نان فانتزی صبا",
    resturantImage: "/images/AllData/R14.jpg",
    foodImage: "/images/AllData/RF14.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "شیرینی ,نان , کیک",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 770,
    },
    freeDeliverByOrder: true,
    category: ["شیرینی", "نانوایی"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 38,
    resturantName: "سوپر میوه و سبزی خرد کنی شادی",
    resturantImage: "/images/AllData/R15.jpeg",
    foodImage: "/images/AllData/RF15.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "میوه ,سبزی , سبزی سرخ شده",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 770,
    },
    freeDeliverByOrder: true,
    category: ["میوه"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 39,
    resturantName: "سوپر میوه و سبزی خرد کنی شادی",
    resturantImage: "/images/AllData/R16.png",
    foodImage: "/images/AllData/RF16.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "میوه ,سبزی , سبزی سرخ شده, آب لیمو",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 670,
    },
    freeDeliverByOrder: false,
    category: ["میوه"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 40,
    resturantName: "سوپر میوه چهر فصل (ابن سینا)",
    resturantImage: "/images/AllData/R17.jpg",
    foodImage: "/images/AllData/RF17.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "میوه ,سبزی , سبزی سرخ شده, آب لیمو",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.4,
      usersVotesCount: 970,
    },
    freeDeliverByOrder: true,
    category: ["میوه"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 41,
    resturantName: "بن آیس طبیعی باش (شهروردی)",
    resturantImage: "/images/AllData/R18.jpg",
    foodImage: "/images/AllData/RF18.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "بستنی ,آبمیوه ,آیس پک ,معجون",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.4,
      usersVotesCount: 970,
    },
    freeDeliverByOrder: false,
    category: ["آبمیوه بستنی"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 42,
    resturantName: "آبمیوه بستنی شهریور",
    resturantImage: "/images/AllData/R19.jpg",
    foodImage: "/images/AllData/RF19.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "بستنی ,آبمیوه ,آیس پک ,معجون",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.4,
      usersVotesCount: 970,
    },
    freeDeliverByOrder: false,
    category: ["آبمیوه بستنی"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 43,
    resturantName: "آبمیوه بستنی شاهور (بلوار کشاورز)",
    resturantImage: "/images/AllData/R20.jpg",
    foodImage: "/images/AllData/RF20.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "بستنی ,آبمیوه ,آیس پک ,معجون",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 270,
    },
    freeDeliverByOrder: false,
    category: ["آبمیوه بستنی"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 44,
    resturantName: "آبمیوه بستنی بهار",
    resturantImage: "/images/AllData/R21.jpg",
    foodImage: "/images/AllData/RF21.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "بستنی ,آبمیوه ,آیس پک ,معجون",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 270,
    },
    freeDeliverByOrder: false,
    category: ["آبمیوه بستنی"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 45,
    resturantName: "آبمیوه بستنی توت فرنگی",
    resturantImage: "/images/AllData/R22.jpg",
    foodImage: "/images/AllData/RF22.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "بستنی ,آبمیوه ,آیس پک ,معجون",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.3,
      usersVotesCount: 270,
    },
    freeDeliverByOrder: false,
    category: ["آبمیوه بستنی"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 46,
    resturantName: "کولاک",
    resturantImage: "/images/AllData/R23.jpg",
    foodImage: "/images/AllData/RF23.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "بستنی ,شیرپسته ,آبمیوه ,آیس پک ,معجون",
    deliveryPrice: 20000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 150,
    },
    freeDeliverByOrder: true,
    category: ["آبمیوه بستنی"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 47,
    resturantName: "گوشت و مرغ محسن",
    resturantImage: "/images/AllData/R24.jpg",
    foodImage: "/images/AllData/RF24.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "مرغ ,گوشت ,گوشت چرخ کرده ,ماهی ,میگو",
    deliveryPrice: 20000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 150,
    },
    freeDeliverByOrder: true,
    category: ["پروتئین"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 48,
    resturantName: "پروتئین زی خوراک شعبه شریعتی",
    resturantImage: "/images/AllData/R25.jpeg",
    foodImage: "/images/AllData/RF25.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "مرغ ,گوشت ,گوشت چرخ کرده ,ماهی ,میگو",
    deliveryPrice: 20000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 150,
    },
    freeDeliverByOrder: true,
    category: ["پروتئین"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 49,
    resturantName: "هایپر پروتئین مای کوئین",
    resturantImage: "/images/AllData/R26.png",
    foodImage: "/images/AllData/RF26.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "مرغ ,گوشت ,گوشت چرخ کرده ,ماهی ,میگو",
    deliveryPrice: 20000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 250,
    },
    freeDeliverByOrder: true,
    category: ["پروتئین"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 50,
    resturantName: "خانه پروتئین بارکو",
    resturantImage: "/images/AllData/R27.jpg",
    foodImage: "/images/AllData/RF27.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "مرغ ,گوشت ,گوشت چرخ کرده ,ماهی ,میگو",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 20,
    },
    freeDeliverByOrder: true,
    category: ["پروتئین"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 51,
    resturantName: "آجیل و شخکبار وزرا",
    resturantImage: "/images/AllData/R28.jpeg",
    foodImage: "/images/AllData/RF28.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "پسته ,بادام ,تخمه ,بادام زمینی",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 20,
    },
    freeDeliverByOrder: true,
    category: ["آجیل"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 52,
    resturantName: "آجیل تواضع",
    resturantImage: "/images/AllData/R29.png",
    foodImage: "/images/AllData/RF29.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "پسته ,بادام ,تخمه ,بادام زمینی",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.9,
      usersVotesCount: 220,
    },
    freeDeliverByOrder: false,
    category: ["آجیل"],
    filterBtns: ["discount", "express"],
  },
  {
    id: 53,
    resturantName: "آجیل و خشکبار رویال شعبه 2",
    resturantImage: "/images/AllData/R30.jpg",
    foodImage: "/images/AllData/RF30.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "پسته ,بادام ,تخمه ,بادام زمینی",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.4,
      usersVotesCount: 220,
    },
    freeDeliverByOrder: false,
    category: ["آجیل"],
    filterBtns: ["discount", "express"],
  },
];

export const sideBarData = [
  {
    id: 1,
    categoryName: "غذا",
    categoryImage: "/images/SideBar/IM1.png",
  },
  {
    id: 2,
    categoryName: "نوشیدنی گرم",
    categoryImage: "/images/SideBar/IM2.png",
  },
  {
    id: 3,
    categoryName: "نوشیدنی سرد",
    categoryImage: "/images/SideBar/IM3.png",
  },
  {
    id: 4,
    categoryName: "کیک و دسر",
    categoryImage: "/images/SideBar/IM4.png",
  },
  {
    id: 5,
    categoryName: "بستنی",
    categoryImage: "/images/SideBar/IM5.png",
  },
];
