export const bannerCategoryData = [
  {
    id: 1,
    imagePath: "/images/Category-img1.png",
    title: "پروتِین",
  },
  {
    id: 2,
    imagePath: "/images/Category-img2.png",
    title: "آبمیوه بستنی",
  },
  {
    id: 3,
    imagePath: "/images/Category-img3.png",
    title: "آجیل",
  },
  {
    id: 4,
    imagePath: "/images/Category-img4.png",
    title: "سایر",
  },
  {
    id: 5,
    imagePath: "/images/Category-img5.png",
    title: "میوه",
  },
  {
    id: 6,
    imagePath: "/images/Category-img6.png",
    title: "نانوایی",
  },
  {
    id: 7,
    imagePath: "/images/Category-img7.png",
    title: "شیرینی",
  },
  {
    id: 8,
    imagePath: "/images/Category-img8.png",
    title: "کافه",
  },
  {
    id: 9,
    imagePath: "/images/Category-img9.png",
    title: "سوپرمارکت",
  },
  {
    id: 10,
    imagePath: "/images/Category-img10.png",
    title: "رستوران",
  },
];

export const foodCategoryData = [
  {
    categoryId: 1,
    name: "ایرانی",
    categoryImage: "/images/Cimage/R1.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی"],
      },
      {
        Id: 2,
        title: "چلوپز سهروردی",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 2,
    name: "فست فود",
    categoryImage: "/images/Cimage/R2.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 3,
    name: "کباب",
    categoryImage: "/images/Cimage/R3.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 4,
    name: "پیتزا",
    categoryImage: "/images/Cimage/R4.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 5,
    name: "برگر",
    categoryImage: "/images/Cimage/R5.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 6,
    name: "ساندویچ",
    categoryImage: "/images/Cimage/R6.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 7,
    name: "سوخاری",
    categoryImage: "/images/Cimage/R7.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 8,
    name: "پاستا",
    categoryImage: "/images/Cimage/R8.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 9,
    name: "سالاد",
    categoryImage: "/images/Cimage/R9.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 10,
    name: "دریایی",
    categoryImage: "/images/Cimage/R10.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 11,
    name: "بین الملل",
    categoryImage: "/images/Cimage/R11.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
  {
    categoryId: 12,
    name: "گیلانی",
    categoryImage: "/images/Cimage/R12.jpg",
    rsturantData: [
      {
        Id: 1,
        title: "کبابی بهار",
        image: "",
        discountRate: "30%",
        rating: 4.5,
        category: ["ایرانی", "کباب", "سنتی", "چلو خورشت"],
      },
    ],
  },
];
export const DiscountData = [
  {
    id: 1,
    resturantName: "فست فود آریا",
    image: "/images/DiscountImage/DiscountFood2.jpeg",
    foodName: "ساندویچ شاورما مرغ",
    deliveryPrice: 15000,
    price: 120000,
    discountRange: 10,
    countInStock: 12,
    rate: 2.5,
    foodIngredients: "۲۰۰ گرم سینه مرغ، کاهو، گوجه فرنگی، خیارشور، نان باگت",
  },
  {
    id: 2,
    resturantName: "فست فود آریا",
    image: "/images/DiscountImage/DiscountFood1.jpeg",
    foodName: "ساندویچ شاورما مرغ",
    deliveryPrice: 15000,
    price: 120000,
    discountRange: 10,
    countInStock: 12,
    rate: 2.5,
    foodIngredients: "۲۰۰ گرم سینه مرغ، کاهو، گوجه فرنگی، خیارشور، نان باگت",
  },
  {
    id: 3,
    resturantName: "فست فود آریا",
    image: "/images/DiscountImage/DiscountFood3.jpeg",
    foodName: "برگر با قارچ و پنیر پیتزا",
    deliveryPrice: 15000,
    price: 220000,
    discountRange: 10,
    countInStock: 12,
    rate: 2.5,
    foodIngredients:
      "یک عدد همبرگر ۹۰ درصد با گوشت گوساله ۱۶۰ گرمی، کاهو، گوجه فرنگی، خیارشور، نان باگت، دو عدد سس تک نفره، سیب زمینی سرخ شده، و یک عدد نوشابه کوکا بطری",
  },
  {
    id: 4,
    resturantName: "فست فود آریا",
    image: "/images/DiscountImage/DiscountFood2.jpeg",
    foodName: "ساندویچ شاورما مرغ",
    deliveryPrice: 15000,
    price: 120000,
    discountRange: 10,
    countInStock: 12,
    rate: 2.5,
    foodIngredients: "۲۰۰ گرم سینه مرغ، کاهو، گوجه فرنگی، خیارشور، نان باگت",
  },
  {
    id: 5,
    resturantName: "فست فود آریا",
    image: "/images/DiscountImage/DiscountFood1.jpeg",
    foodName: "ساندویچ شاورما مرغ",
    deliveryPrice: 15000,
    price: 120000,
    discountRange: 10,
    countInStock: 12,
    rate: 2.5,
    foodIngredients: "۲۰۰ گرم سینه مرغ، کاهو، گوجه فرنگی، خیارشور، نان باگت",
  },
  {
    id: 6,
    resturantName: "فست فود آریا",
    image: "/images/DiscountImage/DiscountFood3.jpeg",
    foodName: "برگر با قارچ و پنیر پیتزا",
    deliveryPrice: 15000,
    price: 220000,
    discountRange: 10,
    countInStock: 12,
    rate: 2.5,
    foodIngredients:
      "یک عدد همبرگر ۹۰ درصد با گوشت گوساله ۱۶۰ گرمی، کاهو، گوجه فرنگی، خیارشور، نان باگت، دو عدد سس تک نفره، سیب زمینی سرخ شده، و یک عدد نوشابه کوکا بطری",
  },
];

export const newExperienceResturantData = [
  {
    id: 1,
    resturantName: "مجنمع نان یاقوت",
    resturantImage: "/images/NewExper/R1.jpg",
    foodImage: "/images/NewExper/RF1.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "ایرانی , سنتی",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4.5,
      usersVotesCount: 231,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 2,
    resturantName: "طباخی آمیرزا",
    resturantImage: "/images/NewExper/R2.jpeg",
    foodImage: "/images/NewExper/RF2.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "ایرانی , سنتی",
    deliveryPrice: 6000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 3,
    resturantName: "کافه دکتر کافی",
    resturantImage: "/images/NewExper/R3.jpeg",
    foodImage: "/images/NewExper/RF3.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "صبحانه,میان وعده,نوشیدنی گرم",
    deliveryPrice: 8000,
    rating: {
      ratingValue: 4.5,
      usersVotesCount: 76,
    },
    freeDeliverByOrder: false,
  },
  {
    id: 4,
    resturantName: "کافه رستوران گفتارخانه",
    resturantImage: "/images/NewExper/R4.jpg",
    foodImage: "/images/NewExper/RF4.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "ایرانی , سنتی",
    deliveryPrice: 16000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 5,
    resturantName: "قنادی هلر",
    resturantImage: "/images/NewExper/R5.jpg",
    foodImage: "/images/NewExper/RF5.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "ایرانی , سنتی",
    deliveryPrice: 6000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 128,
    },
    freeDeliverByOrder: false,
  },
];

export const topRatedData = [
  {
    id: 1,
    resturantName: "پیتزا سیب 360(عباس آباد)",
    resturantImage: "/images/TopRated/R1.png",
    foodImage: "/images/TopRated/RF1.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,برگر",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 2,
    resturantName: "پیتزا پرپروک",
    resturantImage: "/images/TopRated/R2.jpg",
    foodImage: "/images/TopRated/RF2.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "فست فود, پیتزا,سالاد",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: false,
  },
  {
    id: 3,
    resturantName: "پیتزا شیلا",
    resturantImage: "/images/TopRated/R3.jpg",
    foodImage: "/images/TopRated/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,ساندویچ , پیتزا",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 4,
    resturantName: "کافه رستوران گفتارخانه",
    resturantImage: "/images/TopRated/R4.jpg",
    foodImage: "/images/TopRated/RF4.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "کباب ,ایرانی ,سنتی",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
  },
];

export const withDiscountData = [
  {
    id: 1,
    resturantName: "عطاویچ",
    resturantImage: "/images/WDiscount/R1.jpg",
    foodImage: "/images/WDiscount/RF1.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,برگر",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 2,
    resturantName: "فلفل قرمز - قائم مقام",
    resturantImage: "/images/WDiscount/R2.jpeg",
    foodImage: "/images/WDiscount/RF2.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "فست فود, پیتزا,سالاد",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 3,
    resturantName: "مزه پروتئین",
    resturantImage: "/images/WDiscount/R3.jpg",
    foodImage: "/images/WDiscount/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,ساندویچ , پیتزا",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 4,
    resturantName: "هریک",
    resturantImage: "/images/WDiscount/R4.jpg",
    foodImage: "/images/WDiscount/RF4.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,برگر ,مرغ سوخاری",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 5,
    resturantName: "کباب سرای آنیل",
    resturantImage: "/images/AllData/R3.jpg",
    foodImage: "/images/AllData/RF3.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "کباب ,جوجه کباب ,خورشت , چلو",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 180,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: false,
  },
  {
    id: 6,
    resturantName: "کافه شیرینی پراگ (ایرانشهر)",
    resturantImage: "/images/AllData/R4.png",
    foodImage: "/images/AllData/RF4.png",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "نوشیدنی ,قهوه ,اسموتی , شیرینی",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 210,
    },
    freeDeliverByOrder: false,
    category: "کافه",
    discount: true,
    coupun: true,
    expressDelivery: true,
  },
  {
    id: 7,
    resturantName: "کافه رستوران دلوان",
    resturantImage: "/images/AllData/R5.jpeg",
    foodImage: "/images/AllData/RF5.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "نوشیدنی ,ایرانی , ساندویچ",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 220,
    },
    freeDeliverByOrder: true,
    category: "رستوران-کافه",
    discount: true,
    coupun: true,
    expressDelivery: false,
  },
  {
    id: 8,
    resturantName: "آشپزخانه ظفر",
    resturantImage: "/images/AllData/R6.jpg",
    foodImage: "/images/AllData/RF6.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "سنتی ,ایرانی , خورشت",
    deliveryPrice: 0,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 200,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: true,
  },
  {
    id: 9,
    resturantName: "رستوران ارغوان",
    resturantImage: "/images/AllData/R7.png",
    foodImage: "/images/AllData/RF7.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "سنتی ,ایرانی , کباب",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 300,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: false,
  },
];

export const withCouponData = [
  {
    id: 1,
    resturantName: "چیکن فامیلی(یوسف آباد)",
    resturantImage: "/images/WCoupon/R1.jpg",
    foodImage: "/images/WCoupon/RF1.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,چیکن",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 2,
    resturantName: "رستوران روحی",
    resturantImage: "/images/WCoupon/R2.jpg",
    foodImage: "/images/WCoupon/RF2.jpeg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: " کباب, خورشت ,جوجه کباب",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 3,
    resturantName: "ته چین بار",
    resturantImage: "/images/WCoupon/R3.jpg",
    foodImage: "/images/WCoupon/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "ایرانی ,سنتی , ته چین",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4.4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
  },
  {
    id: 4,
    resturantName: "فست فود توتو",
    resturantImage: "/images/WCoupon/R4.jpg",
    foodImage: "/images/WCoupon/RF4.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,برگر ,مرغ سوخاری",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
  },
];

export const allResturantData = [
  {
    id: 1,
    resturantName: "چیکن فامیلی(یوسف آباد)",
    resturantImage: "/images/WCoupon/R1.jpg",
    foodImage: "/images/WCoupon/RF1.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,چیکن",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 2,
    resturantName: "رستوران روحی",
    resturantImage: "/images/WCoupon/R2.jpg",
    foodImage: "/images/WCoupon/RF2.jpeg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: " کباب, خورشت ,جوجه کباب",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: true,
    coupun: true,
    expressDelivery: true,
    filterBtns: "discount",
  },
  {
    id: 3,
    resturantName: "ته چین بار",
    resturantImage: "/images/WCoupon/R3.jpg",
    foodImage: "/images/WCoupon/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "ایرانی ,سنتی , ته چین",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4.4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 4,
    resturantName: "فست فود توتو",
    resturantImage: "/images/WCoupon/R4.jpg",
    foodImage: "/images/WCoupon/RF4.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,برگر ,مرغ سوخاری",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: true,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 5,
    resturantName: "چیکن فامیلی(یوسف آباد)",
    resturantImage: "/images/WCoupon/R1.jpg",
    foodImage: "/images/WCoupon/RF1.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,چیکن",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: true,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 6,
    resturantName: "رستوران روحی",
    resturantImage: "/images/WCoupon/R2.jpg",
    foodImage: "/images/WCoupon/RF2.jpeg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: " کباب, خورشت ,جوجه کباب",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 7,
    resturantName: "ته چین بار",
    resturantImage: "/images/WCoupon/R3.jpg",
    foodImage: "/images/WCoupon/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "ایرانی ,سنتی , ته چین",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4.4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 8,
    resturantName: "فست فود توتو",
    resturantImage: "/images/WCoupon/R4.jpg",
    foodImage: "/images/WCoupon/RF4.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,برگر ,مرغ سوخاری",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 9,
    resturantName: "عطاویچ",
    resturantImage: "/images/WDiscount/R1.jpg",
    foodImage: "/images/WDiscount/RF1.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,برگر",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 10,
    resturantName: "فلفل قرمز - قائم مقام",
    resturantImage: "/images/WDiscount/R2.jpeg",
    foodImage: "/images/WDiscount/RF2.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "فست فود, پیتزا,سالاد",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: true,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 11,
    resturantName: "مزه پروتئین",
    resturantImage: "/images/WDiscount/R3.jpg",
    foodImage: "/images/WDiscount/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,ساندویچ , پیتزا",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 12,
    resturantName: "هریک",
    resturantImage: "/images/WDiscount/R4.jpg",
    foodImage: "/images/WDiscount/RF4.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,برگر ,مرغ سوخاری",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 13,
    resturantName: "پیتزا سیب 360(عباس آباد)",
    resturantImage: "/images/TopRated/R1.png",
    foodImage: "/images/TopRated/RF1.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود,پیتزا,برگر",
    deliveryPrice: 13000,
    rating: {
      ratingValue: 4.2,
      usersVotesCount: 120,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 14,
    resturantName: "پیتزا پرپروک",
    resturantImage: "/images/TopRated/R2.jpg",
    foodImage: "/images/TopRated/RF2.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "فست فود, پیتزا,سالاد",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.1,
      usersVotesCount: 161,
    },
    freeDeliverByOrder: false,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 15,
    resturantName: "پیتزا شیلا",
    resturantImage: "/images/TopRated/R3.jpg",
    foodImage: "/images/TopRated/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,ساندویچ , پیتزا",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: true,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 16,
    resturantName: "کافه رستوران گفتارخانه",
    resturantImage: "/images/TopRated/R4.jpg",
    foodImage: "/images/TopRated/RF4.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "کباب ,ایرانی ,سنتی",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 17,
    resturantName: "جی کافه",
    resturantImage: "/images/AllData/R1.jpg",
    foodImage: "/images/AllData/RF1.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "صبحانه ,میان وعده ,نوشیدنی",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.3,
      usersVotesCount: 118,
    },
    freeDeliverByOrder: false,
    category: "کافه",
    discount: false,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 18,
    resturantName: "رستوران چهل خانه",
    resturantImage: "/images/AllData/R2.png",
    foodImage: "/images/AllData/RF2.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "صبحانه ,میان وعده ,سنتی, املت",
    deliveryPrice: 19000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 180,
    },
    freeDeliverByOrder: false,
    category: "رستوران-کافه",
    discount: true,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 19,
    resturantName: "کباب سرای آنیل",
    resturantImage: "/images/AllData/R3.jpg",
    foodImage: "/images/AllData/RF3.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "کباب ,جوجه کباب ,خورشت , چلو",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 180,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 20,
    resturantName: "کافه شیرینی پراگ (ایرانشهر)",
    resturantImage: "/images/AllData/R4.png",
    foodImage: "/images/AllData/RF4.png",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "نوشیدنی ,قهوه ,اسموتی , شیرینی",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 210,
    },
    freeDeliverByOrder: false,
    category: "کافه",
    discount: false,
    coupun: true,
    expressDelivery: false,
    filterBtns: "express",
  },
  {
    id: 21,
    resturantName: "کافه رستوران دلوان",
    resturantImage: "/images/AllData/R5.jpeg",
    foodImage: "/images/AllData/RF5.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "نوشیدنی ,ایرانی , ساندویچ",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 220,
    },
    freeDeliverByOrder: true,
    category: "رستوران-کافه",
    discount: true,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 22,
    resturantName: "پیتزا شیلا",
    resturantImage: "/images/TopRated/R3.jpg",
    foodImage: "/images/TopRated/RF3.jpg",
    deliveryType: "پیک فروشنده",
    shortDescription: "فست فود ,ساندویچ , پیتزا",
    deliveryPrice: 18000,
    rating: {
      ratingValue: 4,
      usersVotesCount: 70,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: true,
    coupun: true,
    expressDelivery: false,
    filterBtns: "express",
  },
  {
    id: 23,
    resturantName: "کافه رستوران گفتارخانه",
    resturantImage: "/images/TopRated/R4.jpg",
    foodImage: "/images/TopRated/RF4.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "کباب ,ایرانی ,سنتی",
    deliveryPrice: 10000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 168,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: true,
    coupun: true,
    expressDelivery: false,
    filterBtns: "express",
  },
  {
    id: 24,
    resturantName: "جی کافه",
    resturantImage: "/images/AllData/R1.jpg",
    foodImage: "/images/AllData/RF1.jpeg",
    deliveryType: "پیک فروشنده",
    shortDescription: "صبحانه ,میان وعده ,نوشیدنی",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.3,
      usersVotesCount: 118,
    },
    freeDeliverByOrder: false,
    category: "کافه",
    discount: true,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 25,
    resturantName: "رستوران چهل خانه",
    resturantImage: "/images/AllData/R2.png",
    foodImage: "/images/AllData/RF2.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "صبحانه ,میان وعده ,سنتی, املت",
    deliveryPrice: 19000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 180,
    },
    freeDeliverByOrder: false,
    category: "رستوران-کافه",
    discount: true,
    coupun: true,
    expressDelivery: false,
    filterBtns: "express",
  },
  {
    id: 26,
    resturantName: "کباب سرای آنیل",
    resturantImage: "/images/AllData/R3.jpg",
    foodImage: "/images/AllData/RF3.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "کباب ,جوجه کباب ,خورشت , چلو",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 180,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: false,
    filterBtns: "express",
  },
  {
    id: 27,
    resturantName: "کافه شیرینی پراگ (ایرانشهر)",
    resturantImage: "/images/AllData/R4.png",
    foodImage: "/images/AllData/RF4.png",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "نوشیدنی ,قهوه ,اسموتی , شیرینی",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 210,
    },
    freeDeliverByOrder: false,
    category: "کافه",
    discount: true,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 28,
    resturantName: "کافه رستوران دلوان",
    resturantImage: "/images/AllData/R5.jpeg",
    foodImage: "/images/AllData/RF5.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "نوشیدنی ,ایرانی , ساندویچ",
    deliveryPrice: 15000,
    rating: {
      ratingValue: 4.6,
      usersVotesCount: 220,
    },
    freeDeliverByOrder: true,
    category: "رستوران-کافه",
    discount: true,
    coupun: true,
    expressDelivery: false,
    filterBtns: "express",
  },
  {
    id: 29,
    resturantName: "آشپزخانه ظفر",
    resturantImage: "/images/AllData/R6.jpg",
    foodImage: "/images/AllData/RF6.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "سنتی ,ایرانی , خورشت",
    deliveryPrice: 0,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 200,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: true,
    filterBtns: "express",
  },
  {
    id: 30,
    resturantName: "رستوران ارغوان",
    resturantImage: "/images/AllData/R7.png",
    foodImage: "/images/AllData/RF7.jpg",
    deliveryType: "ارسال اکسپرس",
    shortDescription: "سنتی ,ایرانی , کباب",
    deliveryPrice: 12000,
    rating: {
      ratingValue: 4.8,
      usersVotesCount: 300,
    },
    freeDeliverByOrder: true,
    category: "رستوران",
    discount: false,
    coupun: true,
    expressDelivery: false,
    filterBtns: "express",
  },
];

export const sideBarData = [
  {
    id: 1,
    categoryName: "غذا",
    categoryImage: "/images/SideBar/IM1.png",
  },
  {
    id: 2,
    categoryName: "نوشیدنی گرم",
    categoryImage: "/images/SideBar/IM2.png",
  },
  {
    id: 3,
    categoryName: "نوشیدنی سرد",
    categoryImage: "/images/SideBar/IM3.png",
  },
  {
    id: 4,
    categoryName: "کیک و دسر",
    categoryImage: "/images/SideBar/IM4.png",
  },
  {
    id: 5,
    categoryName: "بستنی",
    categoryImage: "/images/SideBar/IM5.png",
  },
];
